esphome:
  name: ${device_name}
#  includes:
#    - packages/vanne/events.h
  includes:
    - constants.h

  on_boot:
    priority: 800
    then:
      - logger.log: "Boot Device"    
      - lambda: |-
          id(flow_rate) = 0;
          id(flow_volume) = 0;
          id(boot_time_ms) = millis();          
          ESP_LOGI("Boot", "Waiting to connect...");

          id(flow_rate_sensor_ui).publish_state(0.0);
          id(flow_volume_sensor_ui).publish_state(0.0); 



esp32:
  board: esp32dev
  framework:
    type: esp-idf
#   type: arduino
  
logger:
# level: INFO
  level: DEBUG  
  logs:
    wifi: WARN
    api: WARN