esphome:
  name: ${device_name}
#  includes:
#    - packages/vanne/events.h
  includes:
    - constants.h

  on_boot:
    priority: -100
    then:
      - lambda: |-

          ESP_LOGI("BOOT", "Restoring RTC state");

          id(machine_state) = (machine_state_t)id(rtc_machine_state);
          id(vanne_active) = id(rtc_vanne_active);
          id(next_event_index) = id(rtc_next_event_index);
          id(next_irrigation_epoch) = id(rtc_next_irrigation_epoch);
          id(mode_init) = id(rtc_mode_init);

          ESP_LOGI("BOOT", "state=%d vanne=%d event=%d",
                   id(machine_state),
                   id(vanne_active),
                   id(next_event_index));
          id(machine_state) = ST_NEXT_EVENT;
 #     - script.execute: compute_next_event

esp32:
  board: esp32dev
  framework:
    type: esp-idf
#    type: arduino
  
logger:
# level: INFO
  level: DEBUG  
  logs:
    wifi: WARN
    api: WARN
    mqtt: WARN
    ota: WARN
    sensor: WARN
    pulse_counter: WARN
    text_sensor: WARN
    number: WARN
    select: WARN
    scheduler: INFO    
#    switch: WARN